# Generated by Django 5.0.1 on 2024-01-23 10:17

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblogs', '0005_subscribe'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog_Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_name', models.CharField(max_length=30)),
                ('blog_img', models.ImageField(upload_to='images/')),
                ('blog_description', ckeditor_uploader.fields.RichTextUploadingField()),
            ],
        ),
    ]
