# Generated by Django 5.0.1 on 2024-02-03 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblogs', '0009_blog_post_like_btn_blog_post_view_btn'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog_comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_author', models.CharField(max_length=10, null=True)),
                ('blog_comment', models.TextField(max_length=200)),
                ('blog_date', models.DateTimeField(null=True)),
                ('blog_idd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myblogs.blog_post')),
            ],
        ),
    ]
