# Generated by Django 5.0.1 on 2024-02-04 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblogs', '0010_blog_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog_comments',
            name='blog_author',
            field=models.CharField(default=1, max_length=10, unique=True),
            preserve_default=False,
        ),
    ]
