# Generated by Django 5.0.1 on 2024-02-05 10:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblogs', '0011_alter_blog_comments_blog_author'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog_comments',
            old_name='blog_date',
            new_name='comment_date',
        ),
        migrations.AlterField(
            model_name='blog_comments',
            name='blog_author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
