# Generated by Django 5.0.1 on 2024-02-29 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblogs', '0012_rename_blog_date_blog_comments_comment_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog_comments',
            name='blog_comment',
            field=models.CharField(max_length=1000),
        ),
    ]
