# Generated by Django 5.0.1 on 2024-02-29 13:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblogs', '0013_alter_blog_comments_blog_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog_comments',
            name='comment_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
