# Generated by Django 5.0.1 on 2024-02-29 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblogs', '0014_alter_blog_comments_comment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog_comments',
            name='blog_idd',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='myblogs.blog_post'),
        ),
    ]
